---
# tasks file for apache2

    - name: install apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: install python
      ansible.builtin.apt:
        name: python
        state: present

    - name: install php
      ansible.builtin.apt:
        name: php
        state: present

    - name: install libapache2_mod_php
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: present

    - name: install php_mysql
      ansible.builtin.apt:
        name: php-mysql
        state: present

    - name: copy config
      ansible.builtin.copy:
        src: /home/aldenpounders/github/apounders42-csc2510-infrastructure/files/config/apache2.conf
        dest: '{{apache2_conf_dest}}'
        owner: root
        group: root
        mode: 0644

    - name: copy index
      ansible.builtin.copy:
        src: /home/aldenpounders/github/apounders42-csc2510-infrastructure/files/site/index.html
        dest: '{{index_html_dest}}'
        owner: root
        group: root
        mode: 0644

    - name: copy php
      ansible.builtin.copy:
        src: ~/github/apounders42-csc2510-infrastructure/apache2/files/index.php
        dest: '{{index_html_dest}}'
        owner: root
        group: root
        mode: 0644

    - name: create symlink
      ansible.builtin.file:
        src: /etc/apache2/mods-available/headers.load
        dest: /etc/apache2/mods-enabled/headers.load
        state: link
                        
      notify:
        - restart
