---
- name: configure apache2
  hosts: webservers
  become: yes
  roles:
    
    - update_apt
    - apache2

- name: configure mysql
  hosts: db
  become: yes
  roles:

    - mysql

  vars:

    mysql_import_data : "yes"
