---
- hosts: all
  become: yes
  tasks:

    - name: Update APT
      ansible.builtin.apt:
        update_cache: true

    - name: install apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: install python
      ansible.builtin.apt:
        name : python
        state: present

    - name: copy config
      ansible.builtin.copy:
        src: /home/aldenpounders/github/apounders42-csc2510-infrastructure/files/config/apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: 0644

    - name: copy index
      ansible.builtin.copy:
        src: /home/aldenpounders/github/apounders42-csc2510-infrastructure/files/site/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: create symlink
      ansible.builtin.file:
        src: /etc/apache2/mods-available/headers.load
        dest: /etc/apache2/mods-enabled/headers.load
        state: link

    - name: restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
